---
version: '3'
services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9443:9443"

  docker_registry:
    image: docker.io/registry:latest
    container_name: docker-registry
    ports:
      - "5000:5000"

  postgres:
    image: docker.io/postgres:bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "passwd"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000" # service
      - "9001:9001" # web admin console
    command: server /minio_data --console-address ":9001"

  cassandra:
    image: docker.io/cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
      - "9160:9160"

  redis:
    image: docker.io/redis:bullseye
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka-broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongodb:
    image: docker.io/mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
