---
version: '3'
services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # sets default password to "portainer123"
    command: --admin-password "$$2y$$05$$jN8Mg65U9c/ayTY0xgBtuOOfRCZXIsFEVLanbyXe6JB3pQDQ5uHU6"
    ports:
      - "9443:9443"

  postgres:
    image: docker.io/postgres:bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000" # service
      - "9001:9001" # web admin console
    command: server /minio_data --console-address ":9001"

  redis:
    image: docker.io/redis:bullseye
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: docker.io/mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
